// Top-10 holdings (approximate) for each ETF/index.
// Percentages are estimates and may change over time.

export const ETF_HOLDINGS = {
  SPY: [
    { name: 'Apple (AAPL)',          pct: 7.0 },
    { name: 'Microsoft (MSFT)',      pct: 6.5 },
    { name: 'NVIDIA (NVDA)',         pct: 6.0 },
    { name: 'Amazon (AMZN)',         pct: 3.7 },
    { name: 'Meta (META)',           pct: 2.8 },
    { name: 'Alphabet A (GOOGL)',    pct: 2.1 },
    { name: 'Alphabet C (GOOG)',     pct: 1.9 },
    { name: 'Berkshire B (BRK-B)',   pct: 1.7 },
    { name: 'Eli Lilly (LLY)',       pct: 1.6 },
    { name: 'Broadcom (AVGO)',       pct: 1.5 },
  ],
  VOO: [
    { name: 'Apple (AAPL)',          pct: 7.0 },
    { name: 'Microsoft (MSFT)',      pct: 6.5 },
    { name: 'NVIDIA (NVDA)',         pct: 6.0 },
    { name: 'Amazon (AMZN)',         pct: 3.7 },
    { name: 'Meta (META)',           pct: 2.8 },
    { name: 'Alphabet A (GOOGL)',    pct: 2.1 },
    { name: 'Alphabet C (GOOG)',     pct: 1.9 },
    { name: 'Berkshire B (BRK-B)',   pct: 1.7 },
    { name: 'Eli Lilly (LLY)',       pct: 1.6 },
    { name: 'Broadcom (AVGO)',       pct: 1.5 },
  ],
  QQQ: [
    { name: 'Apple (AAPL)',          pct: 9.0 },
    { name: 'Microsoft (MSFT)',      pct: 8.5 },
    { name: 'NVIDIA (NVDA)',         pct: 8.0 },
    { name: 'Amazon (AMZN)',         pct: 5.5 },
    { name: 'Broadcom (AVGO)',       pct: 5.0 },
    { name: 'Meta (META)',           pct: 4.5 },
    { name: 'Tesla (TSLA)',          pct: 3.0 },
    { name: 'Alphabet A (GOOGL)',    pct: 2.7 },
    { name: 'Alphabet C (GOOG)',     pct: 2.5 },
    { name: 'Netflix (NFLX)',        pct: 2.0 },
  ],
  VTI: [
    { name: 'Apple (AAPL)',          pct: 6.5 },
    { name: 'Microsoft (MSFT)',      pct: 6.0 },
    { name: 'NVIDIA (NVDA)',         pct: 5.5 },
    { name: 'Amazon (AMZN)',         pct: 3.5 },
    { name: 'Meta (META)',           pct: 2.5 },
    { name: 'Alphabet A (GOOGL)',    pct: 2.0 },
    { name: 'Berkshire B (BRK-B)',   pct: 1.8 },
    { name: 'Broadcom (AVGO)',       pct: 1.5 },
    { name: 'Eli Lilly (LLY)',       pct: 1.4 },
    { name: 'JPMorgan (JPM)',        pct: 1.3 },
  ],
  GLD: [
    { name: 'זהב פיזי (מוטות LBMA)', pct: 100.0 },
  ],
  AGG: [
    { name: "אג\"ח ממשלת ארה\"ב (Treasury)",   pct: 42.0 },
    { name: 'אג"ח סוכנויות (Agency MBS)',       pct: 25.0 },
    { name: 'אג"ח קונצרניות (Corporate)',        pct: 24.0 },
    { name: 'אג"ח סוכנויות פדרליות',            pct: 4.0  },
    { name: 'CMBS (נדל"ן מסחרי)',               pct: 2.0  },
    { name: 'ABS (נכסים מגובים)',               pct: 1.5  },
    { name: 'אחר',                               pct: 1.5  },
  ],
  EEM: [
    { name: 'Taiwan Semiconductor (TSMC)', pct: 8.5 },
    { name: 'Samsung Electronics',         pct: 3.8 },
    { name: 'Tencent Holdings',            pct: 3.5 },
    { name: 'Alibaba Group',               pct: 2.8 },
    { name: 'PDD Holdings (Pinduoduo)',    pct: 1.8 },
    { name: 'Reliance Industries',         pct: 1.6 },
    { name: 'Meituan',                     pct: 1.5 },
    { name: 'HDFC Bank',                   pct: 1.3 },
    { name: 'SK Hynix',                    pct: 1.1 },
    { name: 'Infosys',                     pct: 1.0 },
  ],
}
