// Top-10 holdings (approximate) for each ETF/index.
// Percentages are estimates and may change over time.

const SP500_TOP10 = [
  { name: 'Apple (AAPL)',        pct: 7.0 },
  { name: 'Microsoft (MSFT)',    pct: 6.5 },
  { name: 'NVIDIA (NVDA)',       pct: 6.0 },
  { name: 'Amazon (AMZN)',       pct: 3.7 },
  { name: 'Meta (META)',         pct: 2.8 },
  { name: 'Alphabet A (GOOGL)',  pct: 2.1 },
  { name: 'Alphabet C (GOOG)',   pct: 1.9 },
  { name: 'Berkshire B (BRK-B)', pct: 1.7 },
  { name: 'Eli Lilly (LLY)',     pct: 1.6 },
  { name: 'Broadcom (AVGO)',     pct: 1.5 },
]

const NASDAQ100_TOP10 = [
  { name: 'Apple (AAPL)',        pct: 9.0 },
  { name: 'Microsoft (MSFT)',    pct: 8.5 },
  { name: 'NVIDIA (NVDA)',       pct: 8.0 },
  { name: 'Amazon (AMZN)',       pct: 5.5 },
  { name: 'Broadcom (AVGO)',     pct: 5.0 },
  { name: 'Meta (META)',         pct: 4.5 },
  { name: 'Tesla (TSLA)',        pct: 3.0 },
  { name: 'Alphabet A (GOOGL)',  pct: 2.7 },
  { name: 'Alphabet C (GOOG)',   pct: 2.5 },
  { name: 'Netflix (NFLX)',      pct: 2.0 },
]

const EAFE_TOP10 = [
  { name: 'Novo Nordisk',        pct: 2.5 },
  { name: 'ASML Holding',        pct: 2.0 },
  { name: 'LVMH',                pct: 1.5 },
  { name: 'Nestle',              pct: 1.5 },
  { name: 'AstraZeneca',         pct: 1.4 },
  { name: 'Samsung Electronics', pct: 1.3 },
  { name: 'Shell',               pct: 1.2 },
  { name: 'HSBC',                pct: 1.1 },
  { name: 'Toyota Motor',        pct: 1.0 },
  { name: 'SAP',                 pct: 1.0 },
]

const BOND_AGG = [
  { name: 'אג"ח ממשלת ארה"ב (Treasury)', pct: 42.0 },
  { name: 'אג"ח סוכנויות (Agency MBS)',   pct: 25.0 },
  { name: 'אג"ח קונצרניות (Corporate)',   pct: 24.0 },
  { name: 'אג"ח סוכנויות פדרליות',        pct: 4.0  },
  { name: 'CMBS (נדל"ן מסחרי)',           pct: 2.0  },
  { name: 'ABS (נכסים מגובים)',           pct: 1.5  },
  { name: 'אחר',                           pct: 1.5  },
]

export const ETF_HOLDINGS = {
  // ── S&P 500 ──────────────────────────────────────────────────────────────
  SPY:  SP500_TOP10,
  VOO:  SP500_TOP10,
  IVV:  SP500_TOP10,
  SPLG: SP500_TOP10,

  // ── NASDAQ 100 ───────────────────────────────────────────────────────────
  QQQ:  NASDAQ100_TOP10,
  QQQM: NASDAQ100_TOP10,

  // ── Total US market ───────────────────────────────────────────────────────
  VTI: [
    { name: 'Apple (AAPL)',        pct: 6.5 },
    { name: 'Microsoft (MSFT)',    pct: 6.0 },
    { name: 'NVIDIA (NVDA)',       pct: 5.5 },
    { name: 'Amazon (AMZN)',       pct: 3.5 },
    { name: 'Meta (META)',         pct: 2.5 },
    { name: 'Alphabet A (GOOGL)',  pct: 2.0 },
    { name: 'Berkshire B (BRK-B)', pct: 1.8 },
    { name: 'Broadcom (AVGO)',     pct: 1.5 },
    { name: 'Eli Lilly (LLY)',     pct: 1.4 },
    { name: 'JPMorgan (JPM)',      pct: 1.3 },
  ],
  ITOT: [
    { name: 'Apple (AAPL)',        pct: 6.5 },
    { name: 'Microsoft (MSFT)',    pct: 6.0 },
    { name: 'NVIDIA (NVDA)',       pct: 5.5 },
    { name: 'Amazon (AMZN)',       pct: 3.5 },
    { name: 'Meta (META)',         pct: 2.5 },
    { name: 'Alphabet A (GOOGL)',  pct: 2.0 },
    { name: 'Berkshire B (BRK-B)', pct: 1.8 },
    { name: 'Broadcom (AVGO)',     pct: 1.5 },
    { name: 'Eli Lilly (LLY)',     pct: 1.4 },
    { name: 'JPMorgan (JPM)',      pct: 1.3 },
  ],

  // ── International developed ───────────────────────────────────────────────
  EFA:  EAFE_TOP10,
  VEA:  EAFE_TOP10,
  VXUS: [
    { name: 'Novo Nordisk',        pct: 1.8 },
    { name: 'ASML Holding',        pct: 1.5 },
    { name: 'Samsung Electronics', pct: 1.4 },
    { name: 'TSMC',                pct: 1.3 },
    { name: 'LVMH',                pct: 1.1 },
    { name: 'Nestle',              pct: 1.1 },
    { name: 'AstraZeneca',         pct: 1.0 },
    { name: 'Shell',               pct: 0.9 },
    { name: 'HSBC',                pct: 0.8 },
    { name: 'Tencent Holdings',    pct: 0.7 },
  ],

  // ── Europe broad ─────────────────────────────────────────────────────────
  VGK: [
    { name: 'Novo Nordisk',        pct: 5.0 },
    { name: 'ASML Holding',        pct: 4.5 },
    { name: 'SAP',                 pct: 3.5 },
    { name: 'Nestle',              pct: 3.0 },
    { name: 'AstraZeneca',         pct: 3.0 },
    { name: 'LVMH',                pct: 2.5 },
    { name: 'Shell',               pct: 2.5 },
    { name: 'TotalEnergies',       pct: 2.0 },
    { name: 'HSBC',                pct: 2.0 },
    { name: 'Siemens',             pct: 1.8 },
  ],
  FEZ: [
    { name: 'ASML Holding',        pct: 9.0 },
    { name: 'LVMH',                pct: 6.5 },
    { name: 'SAP',                 pct: 6.5 },
    { name: 'TotalEnergies',       pct: 4.5 },
    { name: 'Sanofi',              pct: 4.0 },
    { name: 'Siemens',             pct: 4.0 },
    { name: 'Schneider Electric',  pct: 4.0 },
    { name: "L'Oreal",             pct: 3.5 },
    { name: 'Airbus',              pct: 3.0 },
    { name: 'BNP Paribas',         pct: 2.5 },
  ],

  // ── Europe countries ──────────────────────────────────────────────────────
  EWG: [
    { name: 'SAP',                 pct: 16.0 },
    { name: 'Siemens',             pct: 9.0  },
    { name: 'Allianz',             pct: 7.0  },
    { name: 'Deutsche Telekom',    pct: 7.0  },
    { name: 'Munich Re',           pct: 5.0  },
    { name: 'BASF',                pct: 5.0  },
    { name: 'BMW',                 pct: 4.0  },
    { name: 'Infineon',            pct: 4.0  },
    { name: 'Mercedes-Benz',       pct: 4.0  },
    { name: 'DHL Group',           pct: 3.0  },
  ],
  EWQ: [
    { name: 'LVMH',                pct: 13.0 },
    { name: 'TotalEnergies',       pct: 9.0  },
    { name: "L'Oreal",             pct: 8.0  },
    { name: 'Sanofi',              pct: 7.0  },
    { name: 'BNP Paribas',         pct: 6.0  },
    { name: 'Schneider Electric',  pct: 5.0  },
    { name: 'AXA',                 pct: 5.0  },
    { name: 'Airbus',              pct: 5.0  },
    { name: 'Hermes',              pct: 4.0  },
    { name: 'Safran',              pct: 3.0  },
  ],
  EWU: [
    { name: 'AstraZeneca',         pct: 10.0 },
    { name: 'Shell',               pct: 8.0  },
    { name: 'HSBC',                pct: 7.0  },
    { name: 'Unilever',            pct: 5.0  },
    { name: 'BP',                  pct: 4.0  },
    { name: 'Rio Tinto',           pct: 4.0  },
    { name: 'Diageo',              pct: 3.0  },
    { name: 'GSK',                 pct: 3.0  },
    { name: 'BAT',                 pct: 3.0  },
    { name: 'Barclays',            pct: 2.0  },
  ],

  // ── Japan ─────────────────────────────────────────────────────────────────
  EWJ: [
    { name: 'Toyota Motor',        pct: 5.0 },
    { name: 'Sony Group',          pct: 4.0 },
    { name: 'Mitsubishi UFJ',      pct: 4.0 },
    { name: 'Keyence',             pct: 3.0 },
    { name: 'Fast Retailing',      pct: 3.0 },
    { name: 'SoftBank Group',      pct: 3.0 },
    { name: 'Tokyo Electron',      pct: 3.0 },
    { name: 'Shin-Etsu Chemical',  pct: 2.5 },
    { name: 'Nintendo',            pct: 2.5 },
    { name: 'Honda Motor',         pct: 2.0 },
  ],

  // ── Taiwan ────────────────────────────────────────────────────────────────
  EWT: [
    { name: 'TSMC',                pct: 25.0 },
    { name: 'Hon Hai (Foxconn)',   pct: 7.0  },
    { name: 'MediaTek',            pct: 7.0  },
    { name: 'Delta Electronics',   pct: 4.0  },
    { name: 'ASE Technology',      pct: 2.5  },
    { name: 'Largan Precision',    pct: 2.0  },
    { name: 'Cathay Financial',    pct: 2.0  },
    { name: 'Fubon Financial',     pct: 2.0  },
    { name: 'Chunghwa Telecom',    pct: 2.0  },
    { name: 'Uni-President',       pct: 1.5  },
  ],

  // ── China ─────────────────────────────────────────────────────────────────
  MCHI: [
    { name: 'Tencent Holdings',    pct: 13.0 },
    { name: 'Alibaba Group',       pct: 8.0  },
    { name: 'Meituan',             pct: 7.0  },
    { name: 'PDD Holdings',        pct: 4.0  },
    { name: 'JD.com',              pct: 4.0  },
    { name: 'Baidu',               pct: 3.0  },
    { name: 'NetEase',             pct: 2.5  },
    { name: 'China Construction Bank', pct: 2.0 },
    { name: 'CNOOC',               pct: 2.0  },
    { name: 'BYD',                 pct: 2.0  },
  ],
  FXI: [
    { name: 'Tencent Holdings',    pct: 12.0 },
    { name: 'Alibaba Group',       pct: 9.0  },
    { name: 'Meituan',             pct: 7.0  },
    { name: 'China Construction Bank', pct: 6.0 },
    { name: 'ICBC',                pct: 5.0  },
    { name: 'CNOOC',               pct: 5.0  },
    { name: 'China Mobile',        pct: 5.0  },
    { name: 'Baidu',               pct: 4.0  },
    { name: 'Ping An Insurance',   pct: 3.0  },
    { name: 'BYD',                 pct: 3.0  },
  ],
  KWEB: [
    { name: 'Tencent Holdings',    pct: 13.0 },
    { name: 'Alibaba Group',       pct: 10.0 },
    { name: 'Meituan',             pct: 9.0  },
    { name: 'JD.com',              pct: 7.0  },
    { name: 'Baidu',               pct: 7.0  },
    { name: 'PDD Holdings',        pct: 7.0  },
    { name: 'NetEase',             pct: 5.0  },
    { name: 'Trip.com',            pct: 4.0  },
    { name: 'Bilibili',            pct: 3.0  },
    { name: 'Kuaishou',            pct: 2.5  },
  ],

  // ── India ─────────────────────────────────────────────────────────────────
  INDA: [
    { name: 'HDFC Bank',           pct: 12.0 },
    { name: 'Reliance Industries', pct: 10.0 },
    { name: 'Infosys',             pct: 8.0  },
    { name: 'ICICI Bank',          pct: 7.0  },
    { name: 'TCS',                 pct: 6.0  },
    { name: 'Bharti Airtel',       pct: 5.0  },
    { name: 'Axis Bank',           pct: 4.0  },
    { name: 'Wipro',               pct: 3.0  },
    { name: 'HUL',                 pct: 2.5  },
    { name: 'Maruti Suzuki',       pct: 2.0  },
  ],

  // ── Emerging markets ─────────────────────────────────────────────────────
  EEM: [
    { name: 'TSMC',                pct: 8.5 },
    { name: 'Samsung Electronics', pct: 3.8 },
    { name: 'Tencent Holdings',    pct: 3.5 },
    { name: 'Alibaba Group',       pct: 2.8 },
    { name: 'PDD Holdings',        pct: 1.8 },
    { name: 'Reliance Industries', pct: 1.6 },
    { name: 'Meituan',             pct: 1.5 },
    { name: 'HDFC Bank',           pct: 1.3 },
    { name: 'SK Hynix',            pct: 1.1 },
    { name: 'Infosys',             pct: 1.0 },
  ],

  // ── Global all-world ──────────────────────────────────────────────────────
  ACWI: [
    { name: 'Apple (AAPL)',        pct: 5.5 },
    { name: 'Microsoft (MSFT)',    pct: 5.0 },
    { name: 'NVIDIA (NVDA)',       pct: 4.5 },
    { name: 'Amazon (AMZN)',       pct: 2.8 },
    { name: 'Meta (META)',         pct: 2.2 },
    { name: 'Alphabet A (GOOGL)',  pct: 1.5 },
    { name: 'Berkshire B (BRK-B)', pct: 1.2 },
    { name: 'Broadcom (AVGO)',     pct: 1.2 },
    { name: 'TSMC',                pct: 1.0 },
    { name: 'Eli Lilly (LLY)',     pct: 0.9 },
  ],
  VT: [
    { name: 'Apple (AAPL)',        pct: 5.0 },
    { name: 'Microsoft (MSFT)',    pct: 4.5 },
    { name: 'NVIDIA (NVDA)',       pct: 4.0 },
    { name: 'Amazon (AMZN)',       pct: 2.5 },
    { name: 'Meta (META)',         pct: 2.0 },
    { name: 'Alphabet A (GOOGL)',  pct: 1.4 },
    { name: 'Berkshire B (BRK-B)', pct: 1.1 },
    { name: 'Broadcom (AVGO)',     pct: 1.1 },
    { name: 'TSMC',                pct: 1.0 },
    { name: 'Eli Lilly (LLY)',     pct: 0.9 },
  ],

  // ── Sector ETFs ───────────────────────────────────────────────────────────
  XLK: [
    { name: 'Microsoft (MSFT)',    pct: 22.0 },
    { name: 'Apple (AAPL)',        pct: 20.0 },
    { name: 'NVIDIA (NVDA)',       pct: 20.0 },
    { name: 'Broadcom (AVGO)',     pct: 5.5  },
    { name: 'Salesforce (CRM)',    pct: 2.5  },
    { name: 'Oracle (ORCL)',       pct: 2.0  },
    { name: 'AMD',                 pct: 1.8  },
    { name: 'Qualcomm (QCOM)',     pct: 1.5  },
    { name: 'Texas Instruments',   pct: 1.5  },
    { name: 'ServiceNow (NOW)',    pct: 1.5  },
  ],
  VGT: [
    { name: 'Apple (AAPL)',        pct: 18.0 },
    { name: 'NVIDIA (NVDA)',       pct: 17.0 },
    { name: 'Microsoft (MSFT)',    pct: 17.0 },
    { name: 'Broadcom (AVGO)',     pct: 5.0  },
    { name: 'Salesforce (CRM)',    pct: 2.5  },
    { name: 'Oracle (ORCL)',       pct: 2.0  },
    { name: 'AMD',                 pct: 1.8  },
    { name: 'Qualcomm (QCOM)',     pct: 1.5  },
    { name: 'Texas Instruments',   pct: 1.5  },
    { name: 'Accenture (ACN)',     pct: 1.5  },
  ],
  XLE: [
    { name: 'Exxon Mobil (XOM)',   pct: 22.0 },
    { name: 'Chevron (CVX)',       pct: 15.0 },
    { name: 'ConocoPhillips',      pct: 7.0  },
    { name: 'EOG Resources',       pct: 5.0  },
    { name: 'SLB (Schlumberger)',  pct: 4.5  },
    { name: 'Marathon Petroleum',  pct: 4.0  },
    { name: 'Phillips 66',         pct: 3.5  },
    { name: 'Valero Energy',       pct: 3.5  },
    { name: 'Diamondback Energy',  pct: 3.0  },
    { name: 'Williams Cos (WMB)',  pct: 3.0  },
  ],
  XLF: [
    { name: 'Berkshire B (BRK-B)', pct: 14.0 },
    { name: 'JPMorgan (JPM)',      pct: 9.0  },
    { name: 'Visa (V)',            pct: 7.0  },
    { name: 'Mastercard (MA)',     pct: 6.0  },
    { name: 'Goldman Sachs (GS)', pct: 4.0  },
    { name: 'Bank of America',     pct: 4.0  },
    { name: 'Morgan Stanley (MS)', pct: 3.0  },
    { name: 'Wells Fargo (WFC)',   pct: 3.0  },
    { name: 'S&P Global (SPGI)',   pct: 3.0  },
    { name: 'BlackRock (BLK)',     pct: 2.5  },
  ],

  // ── Real estate ───────────────────────────────────────────────────────────
  VNQ: [
    { name: 'Prologis (PLD)',      pct: 8.0 },
    { name: 'American Tower',      pct: 6.5 },
    { name: 'Equinix (EQIX)',      pct: 5.5 },
    { name: 'Welltower (WELL)',    pct: 4.5 },
    { name: 'Digital Realty',      pct: 4.0 },
    { name: 'Public Storage',      pct: 3.5 },
    { name: 'Crown Castle (CCI)',  pct: 3.0 },
    { name: 'Simon Property',      pct: 3.0 },
    { name: 'Realty Income (O)',   pct: 2.5 },
    { name: 'SBA Communications', pct: 2.0 },
  ],

  // ── Gold miners ───────────────────────────────────────────────────────────
  GDX: [
    { name: 'Newmont (NEM)',       pct: 18.0 },
    { name: 'Barrick Gold',        pct: 12.0 },
    { name: 'Agnico Eagle (AEM)',  pct: 9.0  },
    { name: 'Wheaton Precious',    pct: 7.5  },
    { name: 'Franco-Nevada',       pct: 6.0  },
    { name: 'Gold Fields',         pct: 4.5  },
    { name: 'Kinross Gold',        pct: 4.0  },
    { name: 'Pan American Silver', pct: 3.0  },
    { name: 'Royal Gold (RGLD)',   pct: 3.0  },
    { name: 'Harmony Gold',        pct: 2.5  },
  ],

  // ── Dow Jones ─────────────────────────────────────────────────────────────
  DIA: [
    { name: 'UnitedHealth (UNH)',  pct: 10.0 },
    { name: 'Goldman Sachs (GS)', pct: 8.0  },
    { name: 'Microsoft (MSFT)',    pct: 7.0  },
    { name: 'Home Depot (HD)',     pct: 6.0  },
    { name: "McDonald's (MCD)",    pct: 5.0  },
    { name: 'Visa (V)',            pct: 4.5  },
    { name: 'Caterpillar (CAT)',   pct: 4.5  },
    { name: 'Salesforce (CRM)',    pct: 4.0  },
    { name: 'Amgen (AMGN)',        pct: 4.0  },
    { name: 'Boeing (BA)',         pct: 3.5  },
  ],

  // ── Bonds ─────────────────────────────────────────────────────────────────
  AGG:  BOND_AGG,
  BND: [
    { name: 'אג"ח ממשלת ארה"ב (Treasury)', pct: 45.0 },
    { name: 'אג"ח סוכנויות (Agency MBS)',   pct: 22.0 },
    { name: 'אג"ח קונצרניות (Corporate)',   pct: 24.0 },
    { name: 'אג"ח סוכנויות פדרליות',        pct: 5.0  },
    { name: 'CMBS (נדל"ן מסחרי)',           pct: 2.0  },
    { name: 'ABS (נכסים מגובים)',           pct: 1.5  },
    { name: 'אחר',                           pct: 0.5  },
  ],
  TLT: [
    { name: 'US Treasury 4.750% 2053', pct: 5.0 },
    { name: 'US Treasury 4.375% 2043', pct: 4.0 },
    { name: 'US Treasury 3.625% 2053', pct: 4.0 },
    { name: 'US Treasury 4.125% 2051', pct: 3.5 },
    { name: 'US Treasury 1.875% 2051', pct: 3.5 },
    { name: 'US Treasury 2.250% 2052', pct: 3.0 },
    { name: 'US Treasury 3.000% 2048', pct: 3.0 },
    { name: 'US Treasury 3.125% 2043', pct: 2.5 },
    { name: 'US Treasury 2.875% 2043', pct: 2.5 },
    { name: 'US Treasury 3.875% 2040', pct: 2.5 },
  ],
  IEF: [
    { name: 'US Treasury 4.375% 2031', pct: 10.0 },
    { name: 'US Treasury 3.875% 2031', pct: 9.0  },
    { name: 'US Treasury 4.000% 2030', pct: 9.0  },
    { name: 'US Treasury 3.500% 2033', pct: 9.0  },
    { name: 'US Treasury 3.875% 2030', pct: 8.0  },
    { name: 'US Treasury 2.875% 2032', pct: 8.0  },
    { name: 'US Treasury 1.500% 2031', pct: 7.0  },
    { name: 'US Treasury 2.750% 2032', pct: 7.0  },
    { name: 'US Treasury 3.750% 2033', pct: 7.0  },
    { name: 'US Treasury 2.625% 2029', pct: 6.0  },
  ],
  SHY: [
    { name: 'US Treasury 5.000% 2026', pct: 12.0 },
    { name: 'US Treasury 4.625% 2026', pct: 11.0 },
    { name: 'US Treasury 4.875% 2025', pct: 10.0 },
    { name: 'US Treasury 4.375% 2026', pct: 10.0 },
    { name: 'US Treasury 5.000% 2025', pct: 9.0  },
    { name: 'US Treasury 4.250% 2025', pct: 8.0  },
    { name: 'US Treasury 4.125% 2027', pct: 8.0  },
    { name: 'US Treasury 4.500% 2027', pct: 8.0  },
    { name: 'US Treasury 4.625% 2027', pct: 7.0  },
    { name: 'US Treasury 4.750% 2026', pct: 6.0  },
  ],

  // ── Commodities ───────────────────────────────────────────────────────────
  GLD: [{ name: 'זהב פיזי (מוטות LBMA)',   pct: 100.0 }],
  IAU: [{ name: 'זהב פיזי (מוטות LBMA)',   pct: 100.0 }],
  SLV: [{ name: 'כסף פיזי (מוטות LBMA)',   pct: 100.0 }],
}
