// Top-10 holdings (approximate) for each ETF/index.
// Percentages are estimates and may change over time.

const SP500_TOP10 = [
  { name: 'Apple (AAPL)',        pct: 7.0 },
  { name: 'NVIDIA (NVDA)',       pct: 7.0 },
  { name: 'Microsoft (MSFT)',    pct: 6.0 },
  { name: 'Amazon (AMZN)',       pct: 3.5 },
  { name: 'Meta (META)',         pct: 2.5 },
  { name: 'Alphabet A (GOOGL)',  pct: 2.1 },
  { name: 'Alphabet C (GOOG)',   pct: 1.9 },
  { name: 'Berkshire B (BRK-B)', pct: 1.7 },
  { name: 'Eli Lilly (LLY)',     pct: 1.6 },
  { name: 'Broadcom (AVGO)',     pct: 1.5 },
]

const NASDAQ100_TOP10 = [
  { name: 'Apple (AAPL)',        pct: 9.0 },
  { name: 'NVIDIA (NVDA)',       pct: 9.0 },
  { name: 'Microsoft (MSFT)',    pct: 7.5 },
  { name: 'Amazon (AMZN)',       pct: 5.5 },
  { name: 'Broadcom (AVGO)',     pct: 5.0 },
  { name: 'Meta (META)',         pct: 4.5 },
  { name: 'Tesla (TSLA)',        pct: 3.0 },
  { name: 'Alphabet A (GOOGL)',  pct: 2.7 },
  { name: 'Alphabet C (GOOG)',   pct: 2.5 },
  { name: 'Netflix (NFLX)',      pct: 2.0 },
]

const EAFE_TOP10 = [
  { name: 'Novo Nordisk',        pct: 2.0 },
  { name: 'SAP',                 pct: 1.5 },
  { name: 'ASML Holding',        pct: 1.5 },
  { name: 'AstraZeneca',         pct: 1.6 },
  { name: 'Nestle',              pct: 1.5 },
  { name: 'Roche Holding',       pct: 1.2 },
  { name: 'Shell',               pct: 1.2 },
  { name: 'HSBC',                pct: 1.1 },
  { name: 'Toyota Motor',        pct: 1.3 },
  { name: 'LVMH',                pct: 1.1 },
]

const BOND_AGG = [
  { name: 'אג"ח ממשלת ארה"ב (Treasury)', pct: 42.0 },
  { name: 'אג"ח סוכנויות (Agency MBS)',   pct: 25.0 },
  { name: 'אג"ח קונצרניות (Corporate)',   pct: 24.0 },
  { name: 'אג"ח סוכנויות פדרליות',        pct: 4.0  },
  { name: 'CMBS (נדל"ן מסחרי)',           pct: 2.0  },
  { name: 'ABS (נכסים מגובים)',           pct: 1.5  },
  { name: 'אחר',                           pct: 1.5  },
]

export const ETF_HOLDINGS = {
  // ── S&P 500 ──────────────────────────────────────────────────────────────
  SPY:  SP500_TOP10,
  VOO:  SP500_TOP10,
  IVV:  SP500_TOP10,
  SPLG: SP500_TOP10,

  // ── NASDAQ 100 ───────────────────────────────────────────────────────────
  QQQ:  NASDAQ100_TOP10,
  QQQM: NASDAQ100_TOP10,

  // ── Total US market ───────────────────────────────────────────────────────
  VTI: [
    { name: 'Apple (AAPL)',        pct: 6.5 },
    { name: 'Microsoft (MSFT)',    pct: 6.0 },
    { name: 'NVIDIA (NVDA)',       pct: 5.5 },
    { name: 'Amazon (AMZN)',       pct: 3.5 },
    { name: 'Meta (META)',         pct: 2.5 },
    { name: 'Alphabet A (GOOGL)',  pct: 2.0 },
    { name: 'Berkshire B (BRK-B)', pct: 1.8 },
    { name: 'Broadcom (AVGO)',     pct: 1.5 },
    { name: 'Eli Lilly (LLY)',     pct: 1.4 },
    { name: 'JPMorgan (JPM)',      pct: 1.3 },
  ],
  ITOT: [
    { name: 'Apple (AAPL)',        pct: 6.5 },
    { name: 'Microsoft (MSFT)',    pct: 6.0 },
    { name: 'NVIDIA (NVDA)',       pct: 5.5 },
    { name: 'Amazon (AMZN)',       pct: 3.5 },
    { name: 'Meta (META)',         pct: 2.5 },
    { name: 'Alphabet A (GOOGL)',  pct: 2.0 },
    { name: 'Berkshire B (BRK-B)', pct: 1.8 },
    { name: 'Broadcom (AVGO)',     pct: 1.5 },
    { name: 'Eli Lilly (LLY)',     pct: 1.4 },
    { name: 'JPMorgan (JPM)',      pct: 1.3 },
  ],

  // ── International developed ───────────────────────────────────────────────
  EFA:  EAFE_TOP10,
  VEA:  EAFE_TOP10,
  VXUS: [
    { name: 'TSMC',                pct: 1.5 },
    { name: 'Novo Nordisk',        pct: 1.4 },
    { name: 'Samsung Electronics', pct: 1.4 },
    { name: 'ASML Holding',        pct: 1.2 },
    { name: 'AstraZeneca',         pct: 1.1 },
    { name: 'Tencent Holdings',    pct: 1.0 },
    { name: 'Shell',               pct: 1.0 },
    { name: 'HSBC',                pct: 1.0 },
    { name: 'LVMH',                pct: 0.9 },
    { name: 'Nestle',              pct: 0.9 },
  ],

  // ── Europe broad ─────────────────────────────────────────────────────────
  VGK: [
    { name: 'SAP',                 pct: 5.0 },
    { name: 'Novo Nordisk',        pct: 3.5 },
    { name: 'ASML Holding',        pct: 3.5 },
    { name: 'AstraZeneca',         pct: 3.5 },
    { name: 'Nestle',              pct: 3.0 },
    { name: 'Schneider Electric',  pct: 3.0 },
    { name: 'Shell',               pct: 2.5 },
    { name: 'TotalEnergies',       pct: 2.0 },
    { name: 'HSBC',                pct: 2.0 },
    { name: 'LVMH',                pct: 1.8 },
  ],
  FEZ: [
    { name: 'ASML Holding',        pct: 9.0 },
    { name: 'LVMH',                pct: 6.5 },
    { name: 'SAP',                 pct: 6.5 },
    { name: 'TotalEnergies',       pct: 4.5 },
    { name: 'Sanofi',              pct: 4.0 },
    { name: 'Siemens',             pct: 4.0 },
    { name: 'Schneider Electric',  pct: 4.0 },
    { name: "L'Oreal",             pct: 3.5 },
    { name: 'Airbus',              pct: 3.0 },
    { name: 'BNP Paribas',         pct: 2.5 },
  ],

  // ── Europe countries ──────────────────────────────────────────────────────
  EWG: [
    { name: 'SAP',                 pct: 20.0 },
    { name: 'Siemens',             pct: 8.0  },
    { name: 'Allianz',             pct: 7.0  },
    { name: 'Deutsche Telekom',    pct: 6.0  },
    { name: 'Munich Re',           pct: 5.0  },
    { name: 'BMW',                 pct: 4.0  },
    { name: 'Infineon',            pct: 4.0  },
    { name: 'Mercedes-Benz',       pct: 4.0  },
    { name: 'BASF',                pct: 3.0  },
    { name: 'DHL Group',           pct: 3.0  },
  ],
  EWQ: [
    { name: 'LVMH',                pct: 11.0 },
    { name: 'TotalEnergies',       pct: 9.0  },
    { name: "L'Oreal",             pct: 8.0  },
    { name: 'Sanofi',              pct: 7.0  },
    { name: 'Hermes',              pct: 6.0  },
    { name: 'BNP Paribas',         pct: 6.0  },
    { name: 'Schneider Electric',  pct: 5.0  },
    { name: 'AXA',                 pct: 5.0  },
    { name: 'Airbus',              pct: 5.0  },
    { name: 'Safran',              pct: 3.0  },
  ],
  EWU: [
    { name: 'AstraZeneca',         pct: 10.0 },
    { name: 'Shell',               pct: 8.0  },
    { name: 'HSBC',                pct: 7.0  },
    { name: 'Unilever',            pct: 5.0  },
    { name: 'BP',                  pct: 4.0  },
    { name: 'Rio Tinto',           pct: 4.0  },
    { name: 'Diageo',              pct: 3.0  },
    { name: 'GSK',                 pct: 3.0  },
    { name: 'BAT',                 pct: 3.0  },
    { name: 'Barclays',            pct: 2.0  },
  ],

  // ── Japan ─────────────────────────────────────────────────────────────────
  EWJ: [
    { name: 'Toyota Motor',        pct: 5.0 },
    { name: 'Sony Group',          pct: 4.0 },
    { name: 'Mitsubishi UFJ',      pct: 4.0 },
    { name: 'Keyence',             pct: 3.0 },
    { name: 'Fast Retailing',      pct: 3.0 },
    { name: 'SoftBank Group',      pct: 3.0 },
    { name: 'Tokyo Electron',      pct: 3.0 },
    { name: 'Shin-Etsu Chemical',  pct: 2.5 },
    { name: 'Nintendo',            pct: 2.5 },
    { name: 'Honda Motor',         pct: 2.0 },
  ],

  // ── Taiwan ────────────────────────────────────────────────────────────────
  EWT: [
    { name: 'TSMC',                pct: 28.0 },
    { name: 'Hon Hai (Foxconn)',   pct: 6.0  },
    { name: 'MediaTek',            pct: 6.0  },
    { name: 'Delta Electronics',   pct: 3.0  },
    { name: 'ASE Technology',      pct: 2.5  },
    { name: 'Largan Precision',    pct: 2.0  },
    { name: 'Cathay Financial',    pct: 2.0  },
    { name: 'Fubon Financial',     pct: 2.0  },
    { name: 'Chunghwa Telecom',    pct: 2.0  },
    { name: 'Uni-President',       pct: 1.5  },
  ],

  // ── China ─────────────────────────────────────────────────────────────────
  MCHI: [
    { name: 'Tencent Holdings',    pct: 15.0 },
    { name: 'Alibaba Group',       pct: 8.0  },
    { name: 'Meituan',             pct: 6.0  },
    { name: 'PDD Holdings',        pct: 4.0  },
    { name: 'JD.com',              pct: 3.0  },
    { name: 'Baidu',               pct: 3.0  },
    { name: 'NetEase',             pct: 2.5  },
    { name: 'China Construction Bank', pct: 2.0 },
    { name: 'CNOOC',               pct: 2.0  },
    { name: 'BYD',                 pct: 2.0  },
  ],
  FXI: [
    { name: 'Tencent Holdings',    pct: 14.0 },
    { name: 'Alibaba Group',       pct: 9.0  },
    { name: 'Meituan',             pct: 6.0  },
    { name: 'China Construction Bank', pct: 6.0 },
    { name: 'ICBC',                pct: 4.0  },
    { name: 'CNOOC',               pct: 5.0  },
    { name: 'China Mobile',        pct: 5.0  },
    { name: 'Baidu',               pct: 4.0  },
    { name: 'Ping An Insurance',   pct: 3.0  },
    { name: 'BYD',                 pct: 3.0  },
  ],
  KWEB: [
    { name: 'Tencent Holdings',    pct: 16.0 },
    { name: 'Alibaba Group',       pct: 9.0  },
    { name: 'Meituan',             pct: 9.0  },
    { name: 'JD.com',              pct: 6.0  },
    { name: 'Baidu',               pct: 6.0  },
    { name: 'PDD Holdings',        pct: 7.0  },
    { name: 'NetEase',             pct: 5.0  },
    { name: 'Trip.com',            pct: 4.0  },
    { name: 'Bilibili',            pct: 3.0  },
    { name: 'Kuaishou',            pct: 2.5  },
  ],

  // ── India ─────────────────────────────────────────────────────────────────
  INDA: [
    { name: 'HDFC Bank',           pct: 12.0 },
    { name: 'Reliance Industries', pct: 10.0 },
    { name: 'Infosys',             pct: 8.0  },
    { name: 'ICICI Bank',          pct: 7.0  },
    { name: 'TCS',                 pct: 6.0  },
    { name: 'Bharti Airtel',       pct: 6.0  },
    { name: 'Axis Bank',           pct: 4.0  },
    { name: 'Wipro',               pct: 2.0  },
    { name: 'HUL',                 pct: 2.5  },
    { name: 'Maruti Suzuki',       pct: 2.0  },
  ],

  // ── Emerging markets ─────────────────────────────────────────────────────
  EEM: [
    { name: 'TSMC',                pct: 8.5 },
    { name: 'Tencent Holdings',    pct: 4.5 },
    { name: 'Samsung Electronics', pct: 3.5 },
    { name: 'Alibaba Group',       pct: 2.5 },
    { name: 'SK Hynix',            pct: 1.5 },
    { name: 'Reliance Industries', pct: 1.6 },
    { name: 'Meituan',             pct: 1.2 },
    { name: 'HDFC Bank',           pct: 1.3 },
    { name: 'PDD Holdings',        pct: 1.5 },
    { name: 'Infosys',             pct: 1.0 },
  ],

  // ── Global all-world ──────────────────────────────────────────────────────
  ACWI: [
    { name: 'Apple (AAPL)',        pct: 5.5 },
    { name: 'NVIDIA (NVDA)',       pct: 5.5 },
    { name: 'Microsoft (MSFT)',    pct: 4.5 },
    { name: 'Amazon (AMZN)',       pct: 2.5 },
    { name: 'Meta (META)',         pct: 2.0 },
    { name: 'Alphabet A (GOOGL)',  pct: 1.5 },
    { name: 'Broadcom (AVGO)',     pct: 1.2 },
    { name: 'Berkshire B (BRK-B)', pct: 1.1 },
    { name: 'TSMC',                pct: 1.1 },
    { name: 'Eli Lilly (LLY)',     pct: 1.0 },
  ],
  VT: [
    { name: 'Apple (AAPL)',        pct: 5.0 },
    { name: 'NVIDIA (NVDA)',       pct: 5.0 },
    { name: 'Microsoft (MSFT)',    pct: 4.0 },
    { name: 'Amazon (AMZN)',       pct: 2.2 },
    { name: 'Meta (META)',         pct: 1.8 },
    { name: 'Alphabet A (GOOGL)',  pct: 1.4 },
    { name: 'Broadcom (AVGO)',     pct: 1.1 },
    { name: 'Berkshire B (BRK-B)', pct: 1.0 },
    { name: 'TSMC',                pct: 1.1 },
    { name: 'Eli Lilly (LLY)',     pct: 0.9 },
  ],

  // ── Sector ETFs ───────────────────────────────────────────────────────────
  XLK: [
    { name: 'Microsoft (MSFT)',    pct: 22.0 },
    { name: 'Apple (AAPL)',        pct: 20.0 },
    { name: 'NVIDIA (NVDA)',       pct: 20.0 },
    { name: 'Broadcom (AVGO)',     pct: 5.5  },
    { name: 'Salesforce (CRM)',    pct: 2.5  },
    { name: 'Oracle (ORCL)',       pct: 2.0  },
    { name: 'AMD',                 pct: 1.8  },
    { name: 'Qualcomm (QCOM)',     pct: 1.5  },
    { name: 'Texas Instruments',   pct: 1.5  },
    { name: 'ServiceNow (NOW)',    pct: 1.5  },
  ],
  VGT: [
    { name: 'NVIDIA (NVDA)',       pct: 21.0 },
    { name: 'Apple (AAPL)',        pct: 16.0 },
    { name: 'Microsoft (MSFT)',    pct: 15.0 },
    { name: 'Broadcom (AVGO)',     pct: 5.0  },
    { name: 'Salesforce (CRM)',    pct: 2.5  },
    { name: 'Oracle (ORCL)',       pct: 2.0  },
    { name: 'AMD',                 pct: 1.8  },
    { name: 'Qualcomm (QCOM)',     pct: 1.5  },
    { name: 'Texas Instruments',   pct: 1.5  },
    { name: 'Accenture (ACN)',     pct: 1.5  },
  ],
  XLE: [
    { name: 'Exxon Mobil (XOM)',   pct: 22.0 },
    { name: 'Chevron (CVX)',       pct: 15.0 },
    { name: 'ConocoPhillips',      pct: 7.0  },
    { name: 'EOG Resources',       pct: 5.0  },
    { name: 'SLB (Schlumberger)',  pct: 4.5  },
    { name: 'Marathon Petroleum',  pct: 4.0  },
    { name: 'Phillips 66',         pct: 3.5  },
    { name: 'Valero Energy',       pct: 3.5  },
    { name: 'Diamondback Energy',  pct: 3.0  },
    { name: 'Williams Cos (WMB)',  pct: 3.0  },
  ],
  XLF: [
    { name: 'Berkshire B (BRK-B)', pct: 14.0 },
    { name: 'JPMorgan (JPM)',      pct: 9.0  },
    { name: 'Visa (V)',            pct: 7.0  },
    { name: 'Mastercard (MA)',     pct: 6.0  },
    { name: 'Goldman Sachs (GS)', pct: 6.0  },
    { name: 'Bank of America',     pct: 3.0  },
    { name: 'Wells Fargo (WFC)',   pct: 3.0  },
    { name: 'Morgan Stanley (MS)', pct: 2.0  },
    { name: 'S&P Global (SPGI)',   pct: 3.0  },
    { name: 'BlackRock (BLK)',     pct: 2.5  },
  ],

  // ── Real estate ───────────────────────────────────────────────────────────
  VNQ: [
    { name: 'Prologis (PLD)',      pct: 8.0 },
    { name: 'American Tower',      pct: 6.5 },
    { name: 'Equinix (EQIX)',      pct: 5.5 },
    { name: 'Welltower (WELL)',    pct: 4.5 },
    { name: 'Digital Realty',      pct: 4.0 },
    { name: 'Public Storage',      pct: 3.5 },
    { name: 'Crown Castle (CCI)',  pct: 3.0 },
    { name: 'Simon Property',      pct: 3.0 },
    { name: 'Realty Income (O)',   pct: 2.5 },
    { name: 'SBA Communications', pct: 2.0 },
  ],

  // ── Gold miners ───────────────────────────────────────────────────────────
  GDX: [
    { name: 'Newmont (NEM)',       pct: 18.0 },
    { name: 'Barrick Gold',        pct: 12.0 },
    { name: 'Agnico Eagle (AEM)',  pct: 9.0  },
    { name: 'Wheaton Precious',    pct: 7.5  },
    { name: 'Franco-Nevada',       pct: 6.0  },
    { name: 'Gold Fields',         pct: 4.5  },
    { name: 'Kinross Gold',        pct: 4.0  },
    { name: 'Pan American Silver', pct: 3.0  },
    { name: 'Royal Gold (RGLD)',   pct: 3.0  },
    { name: 'Harmony Gold',        pct: 2.5  },
  ],

  // ── Dow Jones ─────────────────────────────────────────────────────────────
  DIA: [
    { name: 'Goldman Sachs (GS)', pct: 10.0 },
    { name: 'UnitedHealth (UNH)',  pct: 8.0  },
    { name: 'Microsoft (MSFT)',    pct: 7.0  },
    { name: 'Home Depot (HD)',     pct: 6.0  },
    { name: "McDonald's (MCD)",    pct: 5.0  },
    { name: 'Visa (V)',            pct: 4.5  },
    { name: 'Caterpillar (CAT)',   pct: 4.5  },
    { name: 'Salesforce (CRM)',    pct: 4.0  },
    { name: 'Amgen (AMGN)',        pct: 4.0  },
    { name: 'Boeing (BA)',         pct: 3.5  },
  ],

  // ── Bonds ─────────────────────────────────────────────────────────────────
  AGG:  BOND_AGG,
  BND: [
    { name: 'אג"ח ממשלת ארה"ב (Treasury)', pct: 45.0 },
    { name: 'אג"ח סוכנויות (Agency MBS)',   pct: 22.0 },
    { name: 'אג"ח קונצרניות (Corporate)',   pct: 24.0 },
    { name: 'אג"ח סוכנויות פדרליות',        pct: 5.0  },
    { name: 'CMBS (נדל"ן מסחרי)',           pct: 2.0  },
    { name: 'ABS (נכסים מגובים)',           pct: 1.5  },
    { name: 'אחר',                           pct: 0.5  },
  ],
  TLT: [
    { name: 'US Treasury 4.750% 2053', pct: 5.0 },
    { name: 'US Treasury 4.375% 2043', pct: 4.0 },
    { name: 'US Treasury 3.625% 2053', pct: 4.0 },
    { name: 'US Treasury 4.125% 2051', pct: 3.5 },
    { name: 'US Treasury 1.875% 2051', pct: 3.5 },
    { name: 'US Treasury 2.250% 2052', pct: 3.0 },
    { name: 'US Treasury 3.000% 2048', pct: 3.0 },
    { name: 'US Treasury 3.125% 2043', pct: 2.5 },
    { name: 'US Treasury 2.875% 2043', pct: 2.5 },
    { name: 'US Treasury 3.875% 2040', pct: 2.5 },
  ],
  IEF: [
    { name: 'US Treasury 4.375% 2031', pct: 10.0 },
    { name: 'US Treasury 3.875% 2031', pct: 9.0  },
    { name: 'US Treasury 4.000% 2030', pct: 9.0  },
    { name: 'US Treasury 3.500% 2033', pct: 9.0  },
    { name: 'US Treasury 3.875% 2030', pct: 8.0  },
    { name: 'US Treasury 2.875% 2032', pct: 8.0  },
    { name: 'US Treasury 1.500% 2031', pct: 7.0  },
    { name: 'US Treasury 2.750% 2032', pct: 7.0  },
    { name: 'US Treasury 3.750% 2033', pct: 7.0  },
    { name: 'US Treasury 2.625% 2029', pct: 6.0  },
  ],
  SHY: [
    { name: 'US Treasury 5.000% 2026', pct: 12.0 },
    { name: 'US Treasury 4.625% 2026', pct: 11.0 },
    { name: 'US Treasury 4.875% 2025', pct: 10.0 },
    { name: 'US Treasury 4.375% 2026', pct: 10.0 },
    { name: 'US Treasury 5.000% 2025', pct: 9.0  },
    { name: 'US Treasury 4.250% 2025', pct: 8.0  },
    { name: 'US Treasury 4.125% 2027', pct: 8.0  },
    { name: 'US Treasury 4.500% 2027', pct: 8.0  },
    { name: 'US Treasury 4.625% 2027', pct: 7.0  },
    { name: 'US Treasury 4.750% 2026', pct: 6.0  },
  ],

  // ── Commodities ───────────────────────────────────────────────────────────
  GLD: [{ name: 'זהב פיזי (מוטות LBMA)',   pct: 100.0 }],
  IAU: [{ name: 'זהב פיזי (מוטות LBMA)',   pct: 100.0 }],
  SLV: [{ name: 'כסף פיזי (מוטות LBMA)',   pct: 100.0 }],

  // ── Europe countries (missing) ────────────────────────────────────────────
  EWI: [
    { name: 'UniCredit',             pct: 10.0 },
    { name: 'Intesa Sanpaolo',       pct: 10.0 },
    { name: 'Enel',                  pct: 10.0 },
    { name: 'ENI',                   pct: 9.0  },
    { name: 'Ferrari',               pct: 8.0  },
    { name: 'Prysmian',              pct: 5.0  },
    { name: 'Generali',              pct: 5.0  },
    { name: 'Leonardo',              pct: 4.0  },
    { name: 'Mediobanca',            pct: 4.0  },
    { name: 'Stellantis',            pct: 3.0  },
  ],
  EWP: [
    { name: 'Inditex (Zara)',        pct: 25.0 },
    { name: 'Iberdrola',             pct: 15.0 },
    { name: 'Santander',             pct: 9.0  },
    { name: 'BBVA',                  pct: 8.0  },
    { name: 'CaixaBank',             pct: 5.0  },
    { name: 'Repsol',                pct: 5.0  },
    { name: 'Telefonica',            pct: 4.0  },
    { name: 'Amadeus IT',            pct: 4.0  },
    { name: 'ACS',                   pct: 2.0  },
    { name: 'Naturgy',               pct: 2.0  },
  ],
  EWL: [
    { name: 'Novartis',              pct: 19.0 },
    { name: 'Nestle',                pct: 16.0 },
    { name: 'Roche',                 pct: 16.0 },
    { name: 'ABB',                   pct: 8.0  },
    { name: 'Zurich Insurance',      pct: 7.0  },
    { name: 'UBS',                   pct: 6.0  },
    { name: 'Lonza',                 pct: 4.0  },
    { name: 'Richemont',             pct: 4.0  },
    { name: 'Holcim',                pct: 3.0  },
    { name: 'Partners Group',        pct: 2.0  },
  ],
  EWN: [
    { name: 'ASML Holding',          pct: 35.0 },
    { name: 'NXP Semiconductors',    pct: 10.0 },
    { name: 'ING Group',             pct: 6.0  },
    { name: 'Stellantis',            pct: 5.0  },
    { name: 'Heineken',              pct: 5.0  },
    { name: 'Wolters Kluwer',        pct: 5.0  },
    { name: 'NN Group',              pct: 3.0  },
    { name: 'Randstad',              pct: 2.0  },
    { name: 'Philips',               pct: 2.0  },
    { name: 'ArcelorMittal',         pct: 1.0  },
  ],
  EWD: [
    { name: 'Investor AB',           pct: 9.0 },
    { name: 'Atlas Copco',           pct: 8.0 },
    { name: 'Volvo',                 pct: 7.0 },
    { name: 'Nordea',                pct: 7.0 },
    { name: 'Ericsson',              pct: 5.0 },
    { name: 'Hexagon',               pct: 5.0 },
    { name: 'H&M',                   pct: 4.0 },
    { name: 'SEB',                   pct: 4.0 },
    { name: 'Sandvik',               pct: 4.0 },
    { name: 'Svenska Handelsbanken', pct: 3.0 },
  ],

  // ── Other country ETFs ────────────────────────────────────────────────────
  EWC: [
    { name: 'Royal Bank of Canada',  pct: 10.0 },
    { name: 'Toronto-Dominion',      pct: 9.0  },
    { name: 'Shopify',               pct: 7.0  },
    { name: 'Enbridge',              pct: 5.0  },
    { name: 'CNR',                   pct: 5.0  },
    { name: 'Scotiabank',            pct: 4.0  },
    { name: 'Brookfield',            pct: 4.0  },
    { name: 'Canadian Natural Res.', pct: 4.0  },
    { name: 'Manulife',              pct: 3.0  },
    { name: 'BCE',                   pct: 2.0  },
  ],
  EWA: [
    { name: 'BHP',                   pct: 12.0 },
    { name: 'Commonwealth Bank',     pct: 10.0 },
    { name: 'CSL',                   pct: 7.0  },
    { name: 'NAB',                   pct: 6.0  },
    { name: 'ANZ',                   pct: 5.0  },
    { name: 'Westpac',               pct: 5.0  },
    { name: 'Macquarie',             pct: 4.0  },
    { name: 'Wesfarmers',            pct: 4.0  },
    { name: 'Fortescue',             pct: 3.0  },
    { name: 'Woolworths',            pct: 2.0  },
  ],
  EWZ: [
    { name: 'Vale',                  pct: 15.0 },
    { name: 'Petrobras',             pct: 14.0 },
    { name: 'Itau Unibanco',         pct: 9.0  },
    { name: 'Bradesco',              pct: 5.0  },
    { name: 'Ambev',                 pct: 5.0  },
    { name: 'B3',                    pct: 4.0  },
    { name: 'WEG',                   pct: 4.0  },
    { name: 'Eletrobras',            pct: 3.0  },
    { name: 'Embraer',               pct: 3.0  },
    { name: 'Localiza',              pct: 2.0  },
  ],
  EWY: [
    { name: 'Samsung Electronics',   pct: 22.0 },
    { name: 'SK Hynix',              pct: 9.0  },
    { name: 'LG Energy Solution',    pct: 5.0  },
    { name: 'Samsung SDI',           pct: 3.0  },
    { name: 'POSCO',                 pct: 3.0  },
    { name: 'Hyundai Motor',         pct: 3.0  },
    { name: 'Kakao',                 pct: 2.0  },
    { name: 'NAVER',                 pct: 3.0  },
    { name: 'Samsung Biologics',     pct: 2.0  },
    { name: 'Kia Motors',            pct: 2.0  },
  ],

  // ── Additional ETFs ───────────────────────────────────────────────────────
  VWO: [
    { name: 'TSMC',                  pct: 8.0 },
    { name: 'Tencent Holdings',      pct: 5.0 },
    { name: 'Samsung Electronics',   pct: 2.5 },
    { name: 'Alibaba Group',         pct: 2.5 },
    { name: 'Reliance Industries',   pct: 2.0 },
    { name: 'PDD Holdings',          pct: 2.0 },
    { name: 'Meituan',               pct: 1.5 },
    { name: 'HDFC Bank',             pct: 1.5 },
    { name: 'SK Hynix',              pct: 1.0 },
    { name: 'Infosys',               pct: 1.0 },
  ],
  INDY: [
    { name: 'HDFC Bank',             pct: 14.0 },
    { name: 'Reliance Industries',   pct: 12.0 },
    { name: 'ICICI Bank',            pct: 9.0  },
    { name: 'TCS',                   pct: 8.0  },
    { name: 'Infosys',               pct: 7.0  },
    { name: 'Axis Bank',             pct: 5.0  },
    { name: 'Bharti Airtel',         pct: 4.0  },
    { name: 'L&T',                   pct: 3.0  },
    { name: 'ITC',                   pct: 3.0  },
    { name: 'Maruti Suzuki',         pct: 2.0  },
  ],
  XLV: [
    { name: 'Eli Lilly (LLY)',       pct: 14.0 },
    { name: 'UnitedHealth (UNH)',    pct: 9.0  },
    { name: 'Johnson & Johnson',     pct: 6.0  },
    { name: 'AbbVie (ABBV)',         pct: 5.0  },
    { name: 'Merck (MRK)',           pct: 5.0  },
    { name: 'Pfizer (PFE)',          pct: 4.0  },
    { name: 'Abbott Labs (ABT)',     pct: 4.0  },
    { name: 'Danaher (DHR)',         pct: 3.0  },
    { name: 'Thermo Fisher',         pct: 3.0  },
    { name: 'Boston Scientific',     pct: 2.0  },
  ],
  XLY: [
    { name: 'Amazon (AMZN)',         pct: 23.0 },
    { name: 'Tesla (TSLA)',          pct: 17.0 },
    { name: 'Home Depot (HD)',       pct: 7.0  },
    { name: 'Booking Holdings',      pct: 5.0  },
    { name: "McDonald's (MCD)",      pct: 4.0  },
    { name: 'Nike (NKE)',            pct: 3.0  },
    { name: "Lowe's (LOW)",          pct: 3.0  },
    { name: 'TJX Companies',         pct: 2.0  },
    { name: 'Hilton',                pct: 2.0  },
    { name: 'Ross Stores',           pct: 2.0  },
  ],
  IWM: [
    { name: 'Sprouts Farmers Market', pct: 0.6 },
    { name: 'Clearfield',             pct: 0.5 },
    { name: 'Lantheus Holdings',      pct: 0.5 },
    { name: 'Covenant Logistics',     pct: 0.5 },
    { name: 'Tenet Healthcare',       pct: 0.5 },
    { name: 'Fabrinet',               pct: 0.4 },
    { name: 'Booz Allen Hamilton',    pct: 0.4 },
    { name: 'Insmed',                 pct: 0.4 },
    { name: 'Five Below',             pct: 0.4 },
    { name: 'Abercrombie & Fitch',    pct: 0.4 },
  ],
  VB: [
    { name: 'Sprouts Farmers Market', pct: 0.6 },
    { name: 'Clearfield',             pct: 0.5 },
    { name: 'Tenet Healthcare',       pct: 0.5 },
    { name: 'Fabrinet',               pct: 0.4 },
    { name: 'Lantheus Holdings',      pct: 0.4 },
    { name: 'Booz Allen Hamilton',    pct: 0.4 },
    { name: 'Insmed',                 pct: 0.4 },
    { name: 'Five Below',             pct: 0.4 },
    { name: 'Abercrombie & Fitch',    pct: 0.3 },
    { name: 'Installed Building Prod.', pct: 0.3 },
  ],
  DXJ: [
    { name: 'Toyota Motor',          pct: 6.0 },
    { name: 'Mitsubishi UFJ',        pct: 5.0 },
    { name: 'Honda Motor',           pct: 5.0 },
    { name: 'Sony Group',            pct: 4.0 },
    { name: 'Keyence',               pct: 4.0 },
    { name: 'SoftBank Group',        pct: 4.0 },
    { name: 'Shin-Etsu Chemical',    pct: 3.0 },
    { name: 'Murata Manufacturing',  pct: 3.0 },
    { name: 'Canon',                 pct: 2.0 },
    { name: 'Nintendo',              pct: 2.0 },
  ],
  ONEQ: [
    { name: 'Apple (AAPL)',          pct: 12.0 },
    { name: 'NVIDIA (NVDA)',         pct: 9.0  },
    { name: 'Microsoft (MSFT)',      pct: 8.0  },
    { name: 'Amazon (AMZN)',         pct: 5.0  },
    { name: 'Meta (META)',           pct: 4.0  },
    { name: 'Broadcom (AVGO)',       pct: 4.0  },
    { name: 'Alphabet A (GOOGL)',    pct: 3.0  },
    { name: 'Alphabet C (GOOG)',     pct: 3.0  },
    { name: 'Tesla (TSLA)',          pct: 3.0  },
    { name: 'Netflix (NFLX)',        pct: 2.0  },
  ],

  // ── US Indices ────────────────────────────────────────────────────────────
  '^GSPC': SP500_TOP10,
  '^IXIC': [
    { name: 'Apple (AAPL)',          pct: 12.0 },
    { name: 'NVIDIA (NVDA)',         pct: 9.0  },
    { name: 'Microsoft (MSFT)',      pct: 8.0  },
    { name: 'Amazon (AMZN)',         pct: 5.0  },
    { name: 'Meta (META)',           pct: 4.0  },
    { name: 'Broadcom (AVGO)',       pct: 4.0  },
    { name: 'Alphabet A (GOOGL)',    pct: 3.0  },
    { name: 'Alphabet C (GOOG)',     pct: 3.0  },
    { name: 'Tesla (TSLA)',          pct: 3.0  },
    { name: 'Netflix (NFLX)',        pct: 2.0  },
  ],
  '^DJI': [
    { name: 'Goldman Sachs (GS)',    pct: 10.0 },
    { name: 'UnitedHealth (UNH)',    pct: 8.0  },
    { name: 'Microsoft (MSFT)',      pct: 7.0  },
    { name: 'Home Depot (HD)',       pct: 6.0  },
    { name: "McDonald's (MCD)",      pct: 5.0  },
    { name: 'Visa (V)',              pct: 4.5  },
    { name: 'Caterpillar (CAT)',     pct: 4.5  },
    { name: 'Salesforce (CRM)',      pct: 4.0  },
    { name: 'Amgen (AMGN)',          pct: 4.0  },
    { name: 'Boeing (BA)',           pct: 3.5  },
  ],
  '^RUT': [
    { name: 'Sprouts Farmers Market', pct: 0.6 },
    { name: 'Clearfield',             pct: 0.5 },
    { name: 'Lantheus Holdings',      pct: 0.5 },
    { name: 'Tenet Healthcare',       pct: 0.5 },
    { name: 'Fabrinet',               pct: 0.4 },
    { name: 'Booz Allen Hamilton',    pct: 0.4 },
    { name: 'Five Below',             pct: 0.4 },
    { name: 'Insmed',                 pct: 0.4 },
    { name: 'Abercrombie & Fitch',    pct: 0.4 },
    { name: 'Chesapeake Energy',      pct: 0.4 },
  ],

  // ── European Indices ──────────────────────────────────────────────────────
  '^FTSE': [
    { name: 'AstraZeneca',           pct: 10.0 },
    { name: 'Shell',                 pct: 8.0  },
    { name: 'HSBC',                  pct: 7.0  },
    { name: 'Unilever',              pct: 5.0  },
    { name: 'BP',                    pct: 4.0  },
    { name: 'Rio Tinto',             pct: 4.0  },
    { name: 'Diageo',                pct: 3.0  },
    { name: 'GSK',                   pct: 3.0  },
    { name: 'BAT',                   pct: 3.0  },
    { name: 'Barclays',              pct: 2.0  },
  ],
  '^GDAXI': [
    { name: 'SAP',                   pct: 19.0 },
    { name: 'Siemens',               pct: 9.0  },
    { name: 'Allianz',               pct: 8.0  },
    { name: 'Deutsche Telekom',      pct: 6.0  },
    { name: 'Munich Re',             pct: 5.0  },
    { name: 'BMW',                   pct: 4.0  },
    { name: 'Infineon',              pct: 4.0  },
    { name: 'Mercedes-Benz',         pct: 4.0  },
    { name: 'BASF',                  pct: 3.0  },
    { name: 'DHL Group',             pct: 3.0  },
  ],
  '^FCHI': [
    { name: 'LVMH',                  pct: 10.0 },
    { name: 'TotalEnergies',         pct: 9.0  },
    { name: "L'Oreal",               pct: 8.0  },
    { name: 'Sanofi',                pct: 7.0  },
    { name: 'Hermes',                pct: 6.0  },
    { name: 'BNP Paribas',           pct: 6.0  },
    { name: 'Schneider Electric',    pct: 5.0  },
    { name: 'AXA',                   pct: 5.0  },
    { name: 'Airbus',                pct: 5.0  },
    { name: 'Safran',                pct: 3.0  },
  ],
  '^STOXX50E': [
    { name: 'ASML Holding',          pct: 9.0 },
    { name: 'SAP',                   pct: 6.5 },
    { name: 'LVMH',                  pct: 6.0 },
    { name: 'Siemens',               pct: 4.5 },
    { name: 'TotalEnergies',         pct: 4.5 },
    { name: 'Schneider Electric',    pct: 4.0 },
    { name: 'Sanofi',                pct: 4.0 },
    { name: 'Airbus',                pct: 4.0 },
    { name: "L'Oreal",               pct: 3.5 },
    { name: 'BNP Paribas',           pct: 3.0 },
  ],

  // ── Asian Indices ─────────────────────────────────────────────────────────
  '^N225': [
    { name: 'Fast Retailing (Uniqlo)', pct: 11.0 },
    { name: 'Tokyo Electron',          pct: 7.0  },
    { name: 'SoftBank Group',          pct: 4.0  },
    { name: 'Fanuc',                   pct: 4.0  },
    { name: 'KDDI',                    pct: 3.0  },
    { name: 'Shin-Etsu Chemical',      pct: 3.0  },
    { name: 'Keyence',                 pct: 3.0  },
    { name: 'Daikin',                  pct: 2.0  },
    { name: 'TDK',                     pct: 2.0  },
    { name: 'Murata Manufacturing',    pct: 2.0  },
  ],
  '^HSI': [
    { name: 'Tencent Holdings',      pct: 10.0 },
    { name: 'HSBC',                  pct: 7.0  },
    { name: 'AIA Group',             pct: 6.0  },
    { name: 'Alibaba Group',         pct: 6.0  },
    { name: 'Meituan',               pct: 5.0  },
    { name: 'HK Exchanges',          pct: 4.0  },
    { name: 'CK Hutchison',          pct: 3.0  },
    { name: 'Bank of China HK',      pct: 3.0  },
    { name: 'China Life',            pct: 3.0  },
    { name: 'Hang Seng Bank',        pct: 1.0  },
  ],
  '^BSESN': [
    { name: 'HDFC Bank',             pct: 14.0 },
    { name: 'Reliance Industries',   pct: 12.0 },
    { name: 'ICICI Bank',            pct: 8.0  },
    { name: 'Infosys',               pct: 8.0  },
    { name: 'TCS',                   pct: 7.0  },
    { name: 'Axis Bank',             pct: 4.0  },
    { name: 'Bharti Airtel',         pct: 4.0  },
    { name: 'SBI',                   pct: 3.0  },
    { name: 'Maruti Suzuki',         pct: 3.0  },
    { name: 'L&T',                   pct: 3.0  },
  ],
  '^KS11': [
    { name: 'Samsung Electronics',   pct: 22.0 },
    { name: 'SK Hynix',              pct: 9.0  },
    { name: 'LG Energy Solution',    pct: 5.0  },
    { name: 'Samsung SDI',           pct: 4.0  },
    { name: 'POSCO',                 pct: 3.0  },
    { name: 'Hyundai Motor',         pct: 3.0  },
    { name: 'NAVER',                 pct: 4.0  },
    { name: 'Kakao',                 pct: 2.0  },
    { name: 'Kia Motors',            pct: 2.0  },
    { name: 'SK Innovation',         pct: 2.0  },
  ],
  '^AXJO': [
    { name: 'BHP',                   pct: 12.0 },
    { name: 'Commonwealth Bank',     pct: 10.0 },
    { name: 'CSL',                   pct: 7.0  },
    { name: 'NAB',                   pct: 6.0  },
    { name: 'ANZ',                   pct: 5.0  },
    { name: 'Westpac',               pct: 5.0  },
    { name: 'Macquarie',             pct: 4.0  },
    { name: 'Wesfarmers',            pct: 4.0  },
    { name: 'Fortescue',             pct: 3.0  },
    { name: 'Woolworths',            pct: 2.0  },
  ],

  // ── Israeli Indices ───────────────────────────────────────────────────────
  '^TA125.TA': [
    { name: 'Check Point Software',  pct: 8.0 },
    { name: 'Bank Hapoalim',         pct: 7.0 },
    { name: 'Bank Leumi',            pct: 6.0 },
    { name: 'Nice Systems',          pct: 5.0 },
    { name: 'Bank Discount',         pct: 4.0 },
    { name: 'Elbit Systems',         pct: 4.0 },
    { name: 'ICL Group',             pct: 3.0 },
    { name: 'Azrieli Group',         pct: 3.0 },
    { name: 'Tower Semiconductor',   pct: 3.0 },
    { name: 'Strauss Group',         pct: 2.0 },
  ],
  '^TA35.TA': [
    { name: 'Check Point Software',  pct: 10.0 },
    { name: 'Bank Hapoalim',         pct: 9.0  },
    { name: 'Bank Leumi',            pct: 8.0  },
    { name: 'Nice Systems',          pct: 7.0  },
    { name: 'Bank Discount',         pct: 5.0  },
    { name: 'Elbit Systems',         pct: 5.0  },
    { name: 'ICL Group',             pct: 4.0  },
    { name: 'Azrieli Group',         pct: 4.0  },
    { name: 'Tower Semiconductor',   pct: 3.0  },
    { name: 'Partner Communications', pct: 2.0 },
  ],
  '^TA90.TA': [
    { name: 'Shufersal',             pct: 3.0 },
    { name: 'Paz Oil',               pct: 3.0 },
    { name: 'Delek Group',           pct: 3.0 },
    { name: 'Phoenix Holdings',      pct: 3.0 },
    { name: 'Migdal Insurance',      pct: 2.0 },
    { name: 'Clal Insurance',        pct: 2.0 },
    { name: 'Israel Corp',           pct: 2.0 },
    { name: 'Airport City',          pct: 2.0 },
    { name: 'Harel Insurance',       pct: 2.0 },
    { name: 'Paz Refining',          pct: 2.0 },
  ],
  '^TELBND.TA': [
    { name: 'אג"ח קונצרניות AA',     pct: 30.0 },
    { name: 'אג"ח קונצרניות AAA',    pct: 25.0 },
    { name: 'אג"ח קונצרניות A',      pct: 25.0 },
    { name: 'אג"ח קונצרניות BBB',    pct: 15.0 },
    { name: 'אחר',                   pct: 5.0  },
  ],
}
